index:
    path: /
    controller: App\Controller\DefaultController::index
#config/routes.yaml
api_auth_login:
    path: /login
    methods:  [POST]
api_auth_logout:
    path: /logout
    methods:  GET   
api:
    prefix: /
    resource: '../src/Controller/api'
fos_user_resetting_request:
    path: /resetting
    controller: 'App\controller\ResettingController'