#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#config/routes.yaml
api_auth_login:
    path: /api/login
    methods:  [POST]
api_auth_logout:
    path: /api/logout
    methods:  GET   
api:
    prefix: /api
    resource: '../src/Controller/api'